### ISSUE TITLE
Incorrect argument type during fillPixmap for StyledBackground

### ISSUE THREAD

**Issue by ericjmcd** [PierreRaybaut/PythonQwt#43] opened 2016-09-14 20:40 UTC
For PyQt5 (not using PySide)
fillPixmap uses a QRect object as an argument to painter.setClipRegion for the StyledBackground case but it should be a QRegion object (line 392).
`if widget.testAttribute(Qt.WA_StyledBackground):
            painter.setClipRegion(rect)`
which can be fixed by importing QRegion from QtGUI and then creating that object inline.
`if widget.testAttribute(Qt.WA_StyledBackground):
            painter.setClipRegion(QRegion(rect))`

**Comment by PierreRaybaut** [comment] 2020-08-02 11:56
Duplicate of #49

**Closed by PierreRaybaut** 2020-08-02 11:56 UTC
